apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  #namespace: boot-admin
  name: boot-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: services-reader
subjects:
  - kind: ServiceAccount
    name: service-account-boot-admin
    namespace: boot-admin
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: namespace-a
  name: service-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: service-account-service-a
    namespace: namespace-a
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: namespace-b
  name: service-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: service-account-service-b
    namespace: namespace-b